# ========================
# DATABASE CONFIG
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/codeMentra_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE CONFIG
# ========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# APP CONFIG
# ========================
spring.application.name=backend
server.port=8080